/*This script creates the Group Manager Role - run directly on the database. An id of 99 has been used for safety which has also been changed in groupmanagerroleid in config file.*/
INSERT INTO mdl_role (id,name,shortname,description,sortorder,archetype)
VALUES (99,'Group manager','groupmanager','<p><strong>Role summary:</strong><br />Group managers are able to access the group administration and group reporting functions for groups they are assigned to by Site managers. In all other respects, Group managers are student and can access courses as students do and cannot assign roles to users.</p>\r\n<p><strong>Assignment:</strong><br />Group managers must be assigned at the system level.</p>',99,'student');
INSERT INTO mdl_role_context_levels (roleid,contextlevel) VALUES (99,10);
INSERT INTO mdl_role_capabilities (contextid, roleid,capability, permission, timemodified, modifierid) VALUES
(1,99,'moodle/blog:manageexternal',1,UNIX_TIMESTAMP(),2),
(1,99,'moodle/blog:search',1,UNIX_TIMESTAMP(),2),
(1,99,'moodle/blog:view',1,UNIX_TIMESTAMP(),2),
(1,99,'moodle/portfolio:export',1,UNIX_TIMESTAMP(),2),
(1,99,'moodle/user:readuserblogs',1,UNIX_TIMESTAMP(),2),
(1,99,'moodle/user:readuserposts',1,UNIX_TIMESTAMP(),2),
(1,99,'enrol/self:unenrolself',1,UNIX_TIMESTAMP(),2),
(1,99,'gradereport/overview:view',1,UNIX_TIMESTAMP(),2),
(1,99,'gradereport/user:view',1,UNIX_TIMESTAMP(),2),
(1,99,'moodle/backup:userinfo',1,UNIX_TIMESTAMP(),2),
(1,99,'moodle/blog:associatecourse',1,UNIX_TIMESTAMP(),2),
(1,99,'moodle/comment:post',1,UNIX_TIMESTAMP(),2),
(1,99,'moodle/comment:view',1,UNIX_TIMESTAMP(),2),
(1,99,'moodle/course:viewparticipants',1,UNIX_TIMESTAMP(),2),
(1,99,'moodle/course:viewscales',1,UNIX_TIMESTAMP(),2),
(1,99,'moodle/grade:view',1,UNIX_TIMESTAMP(),2),
(1,99,'moodle/question:flag',1,UNIX_TIMESTAMP(),2),
(1,99,'moodle/rating:rate',1,UNIX_TIMESTAMP(),2),
(1,99,'moodle/rating:view',1,UNIX_TIMESTAMP(),2),
(1,99,'moodle/rating:viewall',1,UNIX_TIMESTAMP(),2),
(1,99,'moodle/rating:viewany',1,UNIX_TIMESTAMP(),2),
(1,99,'moodle/user:viewdetails',1,UNIX_TIMESTAMP(),2),
(1,99,'mod/assignment:exportownsubmission',1,UNIX_TIMESTAMP(),2),
(1,99,'mod/assignment:submit',1,UNIX_TIMESTAMP(),2),
(1,99,'mod/assignment:view',1,UNIX_TIMESTAMP(),2),
(1,99,'mod/certificate:view',1,UNIX_TIMESTAMP(),2),
(1,99,'mod/chat:chat',1,UNIX_TIMESTAMP(),2),
(1,99,'mod/chat:readlog',1,UNIX_TIMESTAMP(),2),
(1,99,'mod/choice:choose',1,UNIX_TIMESTAMP(),2),
(1,99,'mod/data:comment',1,UNIX_TIMESTAMP(),2),
(1,99,'mod/data:exportownentry',1,UNIX_TIMESTAMP(),2),
(1,99,'mod/data:viewentry',1,UNIX_TIMESTAMP(),2),
(1,99,'mod/data:writeentry',1,UNIX_TIMESTAMP(),2),
(1,99,'mod/feedback:complete',1,UNIX_TIMESTAMP(),2),
(1,99,'mod/feedback:view',1,UNIX_TIMESTAMP(),2),
(1,99,'mod/feedback:viewanalysepage',1,UNIX_TIMESTAMP(),2),
(1,99,'mod/forum:createattachment',1,UNIX_TIMESTAMP(),2),
(1,99,'mod/forum:deleteownpost',1,UNIX_TIMESTAMP(),2),
(1,99,'mod/forum:exportownpost',1,UNIX_TIMESTAMP(),2),
(1,99,'mod/forum:initialsubscriptions',1,UNIX_TIMESTAMP(),2),
(1,99,'mod/forum:replypost',1,UNIX_TIMESTAMP(),2),
(1,99,'mod/forum:startdiscussion',1,UNIX_TIMESTAMP(),2),
(1,99,'mod/forum:viewdiscussion',1,UNIX_TIMESTAMP(),2),
(1,99,'mod/forum:viewrating',1,UNIX_TIMESTAMP(),2),
(1,99,'mod/glossary:comment',1,UNIX_TIMESTAMP(),2),
(1,99,'mod/glossary:exportownentry',1,UNIX_TIMESTAMP(),2),
(1,99,'mod/glossary:write',1,UNIX_TIMESTAMP(),2),
(1,99,'mod/questionnaire:printblank',1,UNIX_TIMESTAMP(),2),
(1,99,'mod/questionnaire:readownresponses',1,UNIX_TIMESTAMP(),2),
(1,99,'mod/questionnaire:submit',1,UNIX_TIMESTAMP(),2),
(1,99,'mod/questionnaire:view',1,UNIX_TIMESTAMP(),2),
(1,99,'mod/quiz:attempt',1,UNIX_TIMESTAMP(),2),
(1,99,'mod/quiz:reviewmyattempts',1,UNIX_TIMESTAMP(),2),
(1,99,'mod/quiz:view',1,UNIX_TIMESTAMP(),2),
(1,99,'mod/scorm:savetrack',1,UNIX_TIMESTAMP(),2),
(1,99,'mod/scorm:skipview',1,UNIX_TIMESTAMP(),2),
(1,99,'mod/scorm:viewscores',1,UNIX_TIMESTAMP(),2),
(1,99,'mod/survey:participate',1,UNIX_TIMESTAMP(),2),
(1,99,'mod/wiki:createpage',1,UNIX_TIMESTAMP(),2),
(1,99,'mod/wiki:editcomment',1,UNIX_TIMESTAMP(),2),
(1,99,'mod/wiki:editpage',1,UNIX_TIMESTAMP(),2),
(1,99,'mod/wiki:viewcomment',1,UNIX_TIMESTAMP(),2),
(1,99,'mod/wiki:viewpage',1,UNIX_TIMESTAMP(),2),
(1,99,'mod/workshop:peerassess',1,UNIX_TIMESTAMP(),2),
(1,99,'mod/workshop:submit',1,UNIX_TIMESTAMP(),2),
(1,99,'mod/workshop:view',1,UNIX_TIMESTAMP(),2),
(1,99,'mod/workshop:viewauthornames',1,UNIX_TIMESTAMP(),2),
(1,99,'mod/workshop:viewauthorpublished',1,UNIX_TIMESTAMP(),2),
(1,99,'mod/workshop:viewpublishedsubmissions',1,UNIX_TIMESTAMP(),2),
(1,99,'moodle/blog:associatemodule',1,UNIX_TIMESTAMP(),2),
(1,99,'block/online_users:viewlist',1,UNIX_TIMESTAMP(),2),
(1,99,'moodle/block:view',1,UNIX_TIMESTAMP(),2),
(1,99,'moodle/site:manageblocks',1,UNIX_TIMESTAMP(),2);

/* Update the Manager Role to Site Manager. No capabilities need changing as it just inherits the previous Manager role  */
UPDATE mdl_role SET name = 'Site Manager' WHERE name = 'Manager';


